# Generated by Django 6.0.4 on 2026-04-22 10:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ParcelaKN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shp_id", models.CharField(blank=True, max_length=40, null=True)),
                ("id_2", models.CharField(blank=True, max_length=40, null=True)),
                ("typppd_kod", models.CharField(blank=True, max_length=40, null=True)),
                ("katuze_kod", models.IntegerField(blank=True, null=True)),
                ("obec_kod", models.IntegerField(blank=True, null=True)),
                ("geom", django.contrib.gis.db.models.fields.PolygonField(srid=5514)),
            ],
        ),
    ]
