# Generated by Django 6.0.4 on 2026-04-22 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ParcelaKN",
            new_name="CadastralParcel",
        ),
    ]
