# Generated by Django 6.0.4 on 2026-04-23 12:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0002_rename_parcelakn_cadastralparcel"),
    ]

    operations = [
        migrations.CreateModel(
            name="FloodZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tok_id", models.FloatField(blank=True, null=True)),
                ("naz_tok", models.CharField(blank=True, max_length=60, null=True)),
                ("idvt", models.FloatField(blank=True, null=True)),
                ("tokrec_id", models.FloatField(blank=True, null=True)),
                ("rec_naz", models.CharField(blank=True, max_length=60, null=True)),
                ("max_utokjn", models.FloatField(blank=True, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PolygonField(dim=3, srid=5514),
                ),
            ],
        ),
    ]
