# Generated by Django 6.0.4 on 2026-04-23 12:28

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0003_floodzone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="floodzone",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                dim=3, srid=5514
            ),
        ),
    ]
